### ISSUE TITLE
freezes on GT2+ arcade rally car select

### ISSUE THREAD

**Issue by plaidman** [CookiePLMonster/GT2-Combined-Disc#3]
When I combine GT2 Plus, I am seeing a freeze when I go into arcade mode -> single player -> rally -> rally car -> navigate to the Peugeot 206 Rally Car. The game freezes when I have the 206 showing. It works fine in the split disc GT2+. I haven't tried on the combined disc for the standard GT2, so the freeze might be there too.

**Comment by CookiePLMonster** [comment]
Good timing! I'm implementing a fix for this as we speak.

![image](https://user-images.githubusercontent.com/7947461/156446207-b724c093-d8a6-4a0a-a183-cf656faf6c9c.png)

This issue is kind of a series of unfortunate events - the crash you're encountering is specific to the US version of GT2 Plus, and it was introduced in beta6 then hotfixed in beta 6.1. However, the hotfix only made it to the Arcade Disc code, but with the Combined Disc the game now uses only the Simulation Disc code, including a previously unused arcade mode. Since the bug wasn't fixed here, it re-appears when Combined Disc is in use.

It will be fixed whenever the next version of GT2+ is out, but I am also currently porting the fix made by beta 6.1 on Arcade Disc to the Sim Disc, and I hope to release an update this week.

**Comment by CookiePLMonster** [comment]
Fixed in 0560d7e0c368a5bd891a2080b3f80928edc43628. Before I make a proper release you can overwrite your `setup.py` with the one from here:
https://github.com/CookiePLMonster/GT2-Combined-Disc/blob/master/setup.py
and re-run the setup script, combining discs again.

**Comment by plaidman** [comment]
Thanks for the explanation and the quick fix! I'll test the new script tonight
